import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend_Giga } from "next/font/google";
import "./globals.css";
import Header from "@/components/navigation/Header";
import { LangProvider } from "@/contexts/LangContext";
import Footer from "@/components/navigation/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexendGiga = Lexend_Giga({
  variable: "--font-lexend-giga",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexendGiga.variable}`}
      >
        <LangProvider>
          <Header />
          {children}
          {/* <Footer /> */}
        </LangProvider>
      </body>
    </html>
  );
}
